version: '3.7'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_PASSWORD: supersecret
      MYSQL_DATABASE: gobookstore
      MYSQL_USER: admin
      MYSQL_RANDOM_ROOT_PASSWORD: "foobar"
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db:
